server:
  port: 3333

spring:
  application:
    name: app-server2

#ribbon配置时长，处理超时
ribbon:
  eureka:
    enabled: true
  hystrix:
    enabled: false
  ConnectTimeout: 20000
  ReadTimeout: 20000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 3
  MaxAutoRetries: 3

eureka:
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5   #心跳间隔设置  5秒
      lease-expiration-duration-in-seconds: 10  #没有心跳的淘汰时间设计 10秒
    client:
      service-url:
        defaultZone:  http://wsb:wsb@localhost:1111/eureka/  #中间件注册中心配置，默认使用用户密码登录
      registry-fetch-interval-seconds: 5 #定时刷新本地环境时间设置

logging:
  level:
   com.app: debug
