server:
  port: 1111

#中间件注册中心用户配置
spring:
  security:
    user:
      name: wsb
      password: wsb
  application:
    name: app-eureka

#注册中心服务注册与发现注册
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5  # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间
  client:
    service-url:
       defaultZone: http://wsb:wsb@localhost:1111/eureka/ #中间件注册中地址，默认使用用户名wsb，密码wsb进入
    register-with-eureka: false
    fetch-registry: false
    eureka-service-url-poll-interval-seconds: 60 # 客户端从Eureka Server集群里更新Eureka Server信息的频率
  server:
    enable-self-preservation: true  #关闭自我保护
    eviction-interval-timer-in-ms: 5000 #主动失效检测间隔，配置5秒
    use-read-only-response-cache: false # 禁用readOnlyCacheMap

#日志配置
logging:
  level:
    com.app: debug